/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksPremiumTickRouteImport } from './routes/api/public/hooks/premium-tick'
import { Route as ApiPublicHooksBroadcastTickRouteImport } from './routes/api/public/hooks/broadcast-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPremiumTickRoute =
  ApiPublicHooksPremiumTickRouteImport.update({
    id: '/api/public/hooks/premium-tick',
    path: '/api/public/hooks/premium-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBroadcastTickRoute =
  ApiPublicHooksBroadcastTickRouteImport.update({
    id: '/api/public/hooks/broadcast-tick',
    path: '/api/public/hooks/broadcast-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/broadcast-tick': typeof ApiPublicHooksBroadcastTickRoute
  '/api/public/hooks/premium-tick': typeof ApiPublicHooksPremiumTickRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/broadcast-tick': typeof ApiPublicHooksBroadcastTickRoute
  '/api/public/hooks/premium-tick': typeof ApiPublicHooksPremiumTickRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/broadcast-tick': typeof ApiPublicHooksBroadcastTickRoute
  '/api/public/hooks/premium-tick': typeof ApiPublicHooksPremiumTickRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/hooks/broadcast-tick'
    | '/api/public/hooks/premium-tick'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/hooks/broadcast-tick'
    | '/api/public/hooks/premium-tick'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/hooks/broadcast-tick'
    | '/api/public/hooks/premium-tick'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksBroadcastTickRoute: typeof ApiPublicHooksBroadcastTickRoute
  ApiPublicHooksPremiumTickRoute: typeof ApiPublicHooksPremiumTickRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/premium-tick': {
      id: '/api/public/hooks/premium-tick'
      path: '/api/public/hooks/premium-tick'
      fullPath: '/api/public/hooks/premium-tick'
      preLoaderRoute: typeof ApiPublicHooksPremiumTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/broadcast-tick': {
      id: '/api/public/hooks/broadcast-tick'
      path: '/api/public/hooks/broadcast-tick'
      fullPath: '/api/public/hooks/broadcast-tick'
      preLoaderRoute: typeof ApiPublicHooksBroadcastTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksBroadcastTickRoute: ApiPublicHooksBroadcastTickRoute,
  ApiPublicHooksPremiumTickRoute: ApiPublicHooksPremiumTickRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
